### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by dragondagda** [bastinat0r/Spaceapi_Visualisation#18]
The URL http://spacestatus.bastinat0r.de/ returns 502 Bad Gateway. Was the site moved? Where can I find it now?

**Comment by bastinat0r** [comment]
Yes it has, you can find it at http://spaceapi-stats.n39.eu/

**Comment by dragondagda** [comment]
Thanks for the reply! Do you know who to contact for http://spaceapi.net/app ? There the url is also still wrong.

**Comment by bastinat0r** [comment]
Not really but I have the old app with the old data running on the location again, but I wont fix the bugs there, there is a link to the new site.

**Comment by bastinat0r** [comment]
I do believe the maintanance for spaceapi.net is running a bit low, because they people doing it have more work to do then when it started or something. And they would appreciate some assistance ;)

**Comment by dragondagda** [comment]
do you know who to contact on assistance? I couldn't find any contact information

**Comment by bastinat0r** [comment]
You can try the channel #spaceapi on freenode.
